version: '3'
services:
  unicorn:
    build:
      context: .
      dockerfile: ./containers/unicorn/Dockerfile
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tokyo"
    restart: unless-stopped
